Update Guides “setting-up-a-new-project”
dxw/playbook pull request #962
Opened 2022-07-22 08:20 UTC by claredxw

Automatically generated by Netlify CMS

2022-07-22 10:41 UTC, rjw1 requested changes

2022-07-22 10:41 UTC, rjw1 commented on _guides/setting-up-a-new-project.md
> +* We use of the service standard from the outset of all projects we do, which includes security considerations. Project leads use this as prompts at the start and throughout projects, so security is
```suggestion
* We use the service standard from the outset of all projects we do, which includes security considerations. Project leads use this as prompts at the start and throughout projects, so security is considered as part of the process
```

2022-08-19 12:31 UTC, james approved these changes

2022-08-19 13:06 UTC, rjw1 approved these changes

2022-08-19 13:06 UTC, merged